### ISSUE TITLE
"the docs" link on launcher page doesn't lead anywhere

### ISSUE THREAD

**Issue by ultimike** [ddev/ddev-gitpod-launcher#29]
I just noticed the "the docs" link on https://ddev.github.io/ddev-gitpod-launcher/ leads to a 404 page: https://ddev.readthedocs.io/en/latest/users/topics/gitpod

I see the actual docs [here](https://github.com/ddev/ddev-gitpod-launcher/blob/main/docs/index.html), but I'm not sure where they are actually published to...

-mike

**Comment by rfay** [comment]
Thanks for noticing that! All that's needed is a quick PR here to change the link to https://ddev.readthedocs.io/en/latest/users/install/ddev-installation/#gitpod

Or just remove that and point to the README here?

**Comment by ultimike** [comment]
Done - https://github.com/ddev/ddev-gitpod-launcher/pull/31

thanks,
-mike

**Comment by rfay** [comment]
Fixed in 
* #31
