### ISSUE TITLE
Specified artifacts file in form doesn't actually pull the artifacts correctly

### ISSUE THREAD

**Issue by ultimike** [ddev/ddev-gitpod-launcher#30]
I'm trying to use DrupalPod to launch a "ddevdemo" site with a pre-populated database and files directory.

The repositories are:

- https://github.com/ultimike/ddevdemo
- https://github.com/ultimike/ddevdemo-artifacts

But, whenever I try to launch the site, the database and files directory are not automatically imported. I'm pretty sure I'm following the instructions from https://github.com/ddev/ddev-gitpod-launcher, but clearly I'm missing something...

thanks,
-mike

**Comment by rfay** [comment]
Seems to work for me with the defaults. 

Testing using https://ddev.github.io/ddev-gitpod-launcher/ with the defaults, https://github.com/ddev/d10simple and d10simple-artifacts. It worked fine with those. Take a look at the differences between yours and those. 

Can you share the output of what you see happen with gitpod? Does it fail to download them? Something else?

**Comment by ultimike** [comment]
Yeah, I compared my repos with d10simple and it looks like the ddevdemo one is working fine, but when I add ddevdemo-artifacts, after Gitpod is fully launched, I end up on the Drupal installation screen...

-mike

**Comment by rfay** [comment]
I see it loading the database correctly when I try it, but get this, implying that the code or PHP version don't work righ:

> The website encountered an unexpected error. Try again later.<br><br><em class="placeholder">Error</em>: Call to a member function set() on null in <em class="placeholder">Drupal\dynamic_page_cache\EventSubscriber\DynamicPageCacheSubscriber-&gt;onRequest()</em> (line <em class="placeholder">145</em> of <em class="placeholder">core/modules/dynamic_page_cache/src/EventSubscriber/DynamicPageCacheSubscriber.php</em>). <pre class="backtrace">call_user_func(Array, Object, &#039;kernel.request&#039;, Object) (Line: 111)

You can use `ddev mysql` in the `ddevdemo` directory to inspect the database easily. You'll see that there appear to be the right tables there, meaning they got loaded? 119 tables?

It's certainly interesting that my experience is completely different than yours. I'm getting the db loaded just fine, but can't run the site. 

Ah, but I see it getting the wrong artifacts:

> Checking out repository https://github.com/ultimike/ddevdemo
Attempting to get artifacts from https://github.com/ddev/d10simple-artifacts
Cloning into '/tmp/d10simple-artifacts'...
remote: Enumerating objects: 15, done.
remote: Counting objects: 100% (15/15), done.

Maybe there's something wrong with the form.

**Comment by rfay** [comment]
Here's the problem:

<img width="701" alt="image" src="https://github.com/ddev/ddev-gitpod-launcher/assets/112444/4415daa3-649b-415e-a53e-5b4e4de6cf59">

**Comment by rfay** [comment]
If I change the link to
`https://gitpod.io/#DDEV_REPO=https%3A%2F%2Fgithub.com%2Fultimike%2Fddevdemo,DDEV_ARTIFACTS=https%3A%2F%2Fgithub.com%2Fultimike%2Fddevdemo-artifacts/https://github.com/ddev/ddev-gitpod-launcher/`


Now I see the correct:
> Checking out repository https://github.com/ultimike/ddevdemo
Attempting to get artifacts from https://github.com/ultimike/ddevdemo-artifacts
Cloning into '/tmp/ddevdemo-artifacts'...
remote: Enumerating objects: 7, done.


AND...

<img width="961" alt="image" src="https://github.com/ddev/ddev-gitpod-launcher/assets/112444/3dd4d693-aece-4aa8-b4f1-dd86e100e9a6">

**Comment by rfay** [comment]
I imagine there's something wrong with https://github.com/ddev/ddev-gitpod-launcher/blob/main/docs/script.js ?

**Comment by rfay** [comment]
Thanks for the report (and the PR). I ended up using @shaal 's more extensive PR.

I manually tested and this is working fine now:

<img width="593" alt="image" src="https://github.com/ddev/ddev-gitpod-launcher/assets/112444/54081f43-da39-4167-beb7-f8f75a6c7fef">

<img width="1010" alt="image" src="https://github.com/ddev/ddev-gitpod-launcher/assets/112444/493880aa-20f7-4079-a3ae-6a7307dcf2db">
